name: WF

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run tests
        run: python -m unittest tests/test_Camera.py tests/test_Device.py tests/test_Fridge.py tests/test_Heater.py tests/test_JsonDatabase.py tests/test_Light.py tests/test_Lock.py tests/test_read_write.py
